INSERT INTO university (korean_name, campus)
VALUES ('국립금오공과대학교', 'MAIN'),
       ('국립목포대학교', 'MAIN'),
       ('국립목포해양대학교', 'MAIN'),
       ('국립부경대학교', 'MAIN'),
       ('국립순천대학교', 'MAIN'),
       ('국립창원대학교', 'MAIN'),
       ('국립한국교통대학교', 'MAIN'),
       ('국립한국해양대학교', 'MAIN'),
       ('국립한밭대학교', 'MAIN'),
       ('국민대학교', 'MAIN'),
       ('국제사이버대학교', 'MAIN'),
       ('극동대학교', 'MAIN'),
       ('글로벌사이버대학교', 'MAIN'),
       ('금강대학교', 'MAIN'),
       ('김천대학교', 'MAIN'),
       ('나사렛대학교', 'MAIN'),
       ('남부대학교', 'MAIN'),
       ('남서울대학교', 'MAIN'),
       ('남서울대학교(산업대)', 'MAIN'),
       ('단국대학교', 'MAIN'),
       ('단국대학교', 'SECOND'),
       ('대구가톨릭대학교', 'MAIN'),
       ('대구경북과학기술원', 'MAIN'),
       ('대구교육대학교', 'MAIN'),
       ('대구대학교', 'MAIN'),
       ('대구사이버대학교', 'MAIN'),
       ('대구예술대학교', 'MAIN'),
       ('대구외국어대학교', 'MAIN'),
       ('대구한의대학교', 'MAIN'),
       ('대신대학교', 'MAIN'),
       ('대전가톨릭대학교', 'MAIN'),
       ('대전대학교', 'MAIN'),
       ('대전신학대학교', 'MAIN'),
       ('대진대학교', 'MAIN'),
       ('덕성여자대학교', 'MAIN'),
       ('동국대학교', 'MAIN'),
       ('동국대학교(WISE)', 'BRANCH'),
       ('동덕여자대학교', 'MAIN'),
       ('동명대학교', 'MAIN'),
       ('동서대학교', 'MAIN'),
       ('동신대학교', 'MAIN'),
       ('동아대학교', 'MAIN'),
       ('동양대학교', 'MAIN'),
       ('동의대학교', 'MAIN'),
       ('디지털서울문화예술대학교', 'MAIN'),
       ('루터대학교', 'MAIN'),
       ('명지대학교', 'MAIN'),
       ('명지대학교', 'SECOND'),
       ('목원대학교', 'MAIN'),
       ('목포가톨릭대학교', 'MAIN'),
       ('배재대학교', 'MAIN'),
       ('백석대학교', 'MAIN'),
       ('부산가톨릭대학교', 'MAIN'),
       ('부산교육대학교', 'MAIN'),
       ('부산대학교', 'MAIN'),
       ('부산디지털대학교', 'MAIN'),
       ('부산외국어대학교', 'MAIN'),
       ('부산장신대학교', 'MAIN'),
       ('사이버한국외국어대학교', 'MAIN'),
       ('삼육대학교', 'MAIN'),
       ('상명대학교', 'MAIN'),
       ('상명대학교', 'SECOND'),
       ('상지대학교', 'MAIN'),
       ('서강대학교', 'MAIN'),
       ('서경대학교', 'MAIN'),
       ('서남대학교', 'MAIN'),
       ('서남대학교', 'SECOND'),
       ('서울과학기술대학교', 'MAIN'),
       ('서울교육대학교', 'MAIN'),
       ('서울기독대학교', 'MAIN'),
       ('서울대학교', 'MAIN'),
       ('서울디지털대학교', 'MAIN'),
       ('서울사이버대학교', 'MAIN'),
       ('서울시립대학교', 'MAIN'),
       ('서울신학대학교', 'MAIN'),
       ('서울여자대학교', 'MAIN'),
       ('서울장신대학교', 'MAIN'),
       ('서울한영대학교', 'MAIN'),
       ('서원대학교', 'MAIN'),
       ('선문대학교', 'MAIN'),
       ('성결대학교', 'MAIN'),
       ('성공회대학교', 'MAIN'),
       ('성균관대학교', 'MAIN'),
       ('성신여자대학교', 'MAIN'),
       ('세명대학교', 'MAIN'),
       ('세종대학교', 'MAIN'),
       ('세종사이버대학교', 'MAIN'),
       ('세한대학교', 'MAIN'),
       ('송원대학교', 'MAIN'),
       ('수원가톨릭대학교', 'MAIN'),
       ('수원대학교', 'MAIN'),
       ('숙명여자대학교', 'MAIN'),
       ('순복음총회신학교', 'MAIN'),
       ('순천향대학교', 'MAIN'),
       ('숭실대학교', 'MAIN'),
       ('숭실사이버대학교', 'MAIN'),
       ('신경주대학교', 'MAIN'),
       ('신라대학교', 'MAIN'),
       ('신한대학교', 'MAIN'),
       ('신한대학교', 'SECOND'),
       ('아신대학교', 'MAIN'),
       ('아주대학교', 'MAIN'),
       ('안양대학교', 'MAIN'),
       ('안양대학교', 'SECOND'),
       ('연세대학교', 'MAIN'),
       ('연세대학교(미래)', 'BRANCH'),
       ('영남대학교', 'MAIN'),
       ('영남신학대학교', 'MAIN'),
       ('영산대학교(양산)', 'SECOND'),
       ('영산대학교(해운대)', 'MAIN'),
       ('영산선학대학교', 'MAIN'),
       ('예수대학교', 'MAIN'),
       ('예원예술대학교', 'MAIN'),
       ('예원예술대학교', 'SECOND'),
       ('용인대학교', 'MAIN'),
       ('우석대학교', 'MAIN'),
       ('우송대학교', 'MAIN'),
       ('우송대학교(산업대)', 'MAIN'),
       ('울산과학기술원', 'MAIN'),
       ('울산대학교', 'MAIN'),
       ('원광대학교', 'MAIN'),
       ('원광디지털대학교', 'MAIN'),
       ('위덕대학교', 'MAIN'),
       ('유원대학교', 'MAIN'),
       ('을지대학교', 'MAIN'),
       ('을지대학교', 'SECOND'),
       ('을지대학교', 'THIRD'),
       ('이화여자대학교', 'MAIN'),
       ('인제대학교', 'MAIN'),
       ('인제대학교', 'SECOND'),
       ('인천가톨릭대학교', 'MAIN'),
       ('인천가톨릭대학교', 'SECOND'),
       ('인천대학교', 'MAIN'),
       ('인하대학교', 'MAIN'),
       ('장로회신학대학교', 'MAIN'),
       ('전남대학교', 'MAIN'),
       ('전남대학교', 'SECOND'),
       ('전북대학교', 'MAIN'),
       ('전주교육대학교', 'MAIN'),
       ('전주대학교', 'MAIN'),
       ('정석대학', 'MAIN'),
       ('제주국제대학교', 'MAIN'),
       ('제주대학교', 'MAIN'),
       ('조선대학교', 'MAIN'),
       ('중부대학교', 'MAIN'),
       ('중앙대학교', 'MAIN'),
       ('중앙대학교', 'SECOND'),
       ('중앙승가대학교', 'MAIN'),
       ('중원대학교', 'MAIN'),
       ('진주교육대학교', 'MAIN'),
       ('진주산업대학교(산업대)', 'MAIN'),
       ('차의과학대학교', 'MAIN'),
       ('창신대학교', 'MAIN'),
       ('청운대학교', 'MAIN'),
       ('청주교육대학교', 'MAIN'),
       ('청주대학교', 'MAIN'),
       ('초당대학교', 'MAIN'),
       ('총신대학교', 'MAIN'),
       ('추계예술대학교', 'MAIN'),
       ('춘천교육대학교', 'MAIN'),
       ('충남대학교', 'MAIN'),
       ('충북대학교', 'MAIN'),
       ('칼빈대학교', 'MAIN'),
       ('탐라대학교', 'MAIN'),
       ('태재대학교', 'MAIN'),
       ('평택대학교', 'MAIN'),
       ('포항공과대학교', 'MAIN'),
       ('한경국립대학교', 'MAIN'),
       ('한국공학대학교', 'MAIN'),
       ('한국과학기술원', 'MAIN'),
       ('한국교원대학교', 'MAIN'),
       ('한국기술교육대학교', 'MAIN'),
       ('한국방송통신대학교', 'MAIN'),
       ('한국성서대학교', 'MAIN'),
       ('한국에너지공과대학교', 'MAIN'),
       ('한국열린사이버대학교', 'MAIN'),
       ('한국예술종합학교', 'MAIN'),
       ('한국외국어대학교', 'MAIN'),
       ('한국전통문화대학교', 'MAIN'),
       ('한국체육대학교', 'MAIN'),
       ('한국침례신학대학교', 'MAIN'),
       ('한국항공대학교', 'MAIN'),
       ('한남대학교', 'MAIN'),
       ('한동대학교', 'MAIN'),
       ('한라대학교', 'MAIN'),
       ('한려대학교', 'MAIN'),
       ('한림대학교', 'MAIN'),
       ('한밭대학교(산업대)', 'MAIN'),
       ('한북대학교', 'MAIN'),
       ('한서대학교', 'MAIN'),
       ('한성대학교', 'MAIN'),
       ('한세대학교', 'MAIN'),
       ('한신대학교', 'MAIN'),
       ('한양대학교', 'MAIN'),
       ('한양대학교(ERICA)', 'BRANCH'),
       ('한양사이버대학교', 'MAIN'),
       ('한일장신대학교', 'MAIN'),
       ('한중대학교', 'MAIN'),
       ('협성대학교', 'MAIN'),
       ('호남대학교', 'MAIN'),
       ('호남신학대학교', 'MAIN'),
       ('호서대학교', 'MAIN'),
       ('호원대학교', 'MAIN'),
       ('홍익대학교', 'MAIN'),
       ('홍익대학교', 'SECOND'),
       ('화성의과학대학교', 'MAIN'),
       ('화신사이버대학교', 'MAIN'),
       ('ICT폴리텍대학', 'MAIN'),
       ('가톨릭상지대학교', 'MAIN'),
       ('강동대학교', 'MAIN'),
       ('강릉영동대학교', 'MAIN'),
       ('강원관광대학교', 'MAIN'),
       ('강원도립대학교', 'MAIN'),
       ('거제대학교', 'MAIN'),
       ('경기과학기술대학교', 'MAIN'),
       ('가야대학교(고령)', 'SECOND'),
       ('가야대학교(김해)', 'MAIN'),
       ('가천대학교', 'MAIN'),
       ('가톨릭관동대학교', 'MAIN'),
       ('가톨릭꽃동네대학교', 'MAIN'),
       ('가톨릭대학교', 'MAIN'),
       ('가톨릭대학교', 'SECOND'),
       ('가톨릭대학교', 'THIRD'),
       ('감리교신학대학교', 'MAIN'),
       ('강남대학교', 'MAIN'),
       ('강서대학교', 'MAIN'),
       ('강원대학교', 'MAIN'),
       ('강원대학교', 'SECOND'),
       ('건국대학교', 'MAIN'),
       ('건국대학교(글로컬)', 'BRANCH'),
       ('건양대학교', 'MAIN'),
       ('건양대학교', 'SECOND'),
       ('건양사이버대학교', 'MAIN'),
       ('경기대학교', 'MAIN'),
       ('경기대학교', 'SECOND'),
       ('경남과학기술대학교', 'MAIN'),
       ('경남대학교', 'MAIN'),
       ('경동대학교', 'MAIN'),
       ('경동대학교', 'SECOND'),
       ('경동대학교', 'THIRD'),
       ('경동대학교', 'FOURTH'),
       ('경북대학교', 'MAIN'),
       ('경상국립대학교', 'MAIN'),
       ('경성대학교', 'MAIN'),
       ('경운대학교', 'MAIN'),
       ('경운대학교(산업대)', 'MAIN'),
       ('경인교육대학교', 'MAIN'),
       ('경인교육대학교', 'SECOND'),
       ('경일대학교', 'MAIN'),
       ('경희대학교', 'MAIN'),
       ('경희사이버대학교', 'MAIN'),
       ('계명대학교', 'MAIN'),
       ('고려대학교', 'MAIN'),
       ('고려대학교(세종)', 'BRANCH'),
       ('고려사이버대학교', 'MAIN'),
       ('고신대학교', 'MAIN'),
       ('공주교육대학교', 'MAIN'),
       ('광신대학교', 'MAIN'),
       ('광운대학교', 'MAIN'),
       ('광주가톨릭대학교', 'MAIN'),
       ('광주과학기술원', 'MAIN'),
       ('광주교육대학교', 'MAIN'),
       ('광주대학교', 'MAIN'),
       ('광주여자대학교', 'MAIN'),
       ('국립강릉원주대학교', 'MAIN'),
       ('국립강릉원주대학교', 'SECOND'),
       ('국립경국대학교', 'MAIN'),
       ('국립공주대학교', 'MAIN'),
       ('국립군산대학교', 'MAIN');

-- 유저
INSERT INTO users (email, university_id, name, phone_number, student_number, provider, is_marketing_agreement, image_url)
VALUES ('user01@example.com', 1, '홍길동', '010-1000-0001', '20250001', 'GOOGLE', TRUE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user02@example.com', 1, '김철수', '010-1000-0002', '20250002', 'GOOGLE', TRUE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user03@example.com', 1, '이영희', '010-1000-0003', '20250003', 'GOOGLE', TRUE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user04@example.com', 1, '박민수', '010-1000-0004', '20250004', 'GOOGLE', FALSE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user05@example.com', 1, '최서연', '010-1000-0005', '20250005', 'GOOGLE', TRUE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user06@example.com', 1, '정우진', '010-1000-0006', '20250006', 'GOOGLE', FALSE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user07@example.com', 1, '오하늘', '010-1000-0007', '20250007', 'GOOGLE', TRUE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user08@example.com', 1, '윤예진', '010-1000-0008', '20250008', 'GOOGLE', FALSE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user09@example.com', 1, '강도현', '010-1000-0009', '20250009', 'GOOGLE', FALSE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user10@example.com', 1, '신가윤', '010-1000-0010', '20250010', 'GOOGLE', FALSE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user11@example.com', 1, '서하준', '010-1000-0011', '20250011', 'GOOGLE', FALSE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user12@example.com', 1, '문정우', '010-1000-0012', '20250012', 'GOOGLE', TRUE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user13@example.com', 1, '김다은', '010-1000-0013', '20250013', 'GOOGLE', FALSE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user14@example.com', 1, '이주원', '010-1000-0014', '20250014', 'GOOGLE', TRUE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user15@example.com', 1, '박소현', '010-1000-0015', '20250015', 'GOOGLE', TRUE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user16@example.com', 1, '양도균', '010-1000-0016', '20250016', 'GOOGLE', FALSE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user17@example.com', 1, '조하림', '010-1000-0017', '20250017', 'GOOGLE', TRUE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user18@example.com', 1, '한예준', '010-1000-0018', '20250018', 'GOOGLE', FALSE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user19@example.com', 1, '권민재', '010-1000-0019', '20250019', 'GOOGLE', TRUE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png'),
       ('user20@example.com', 1, '임소연', '010-1000-0020', '20250020', 'GOOGLE', TRUE, 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png');

-- 동아리
INSERT INTO club (club_category, university_id, name, description, introduce, image_url, location)
VALUES ('ACADEMIC', 1, 'BCSD', '즐겁게 일하고 열심히 노는 IT 특성화 동아리! 코인 만든 동아리예요~',
        'BCSD는 IT 실무 프로젝트를 경험하며 성장하는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png',
        '학생회관 101호'),
       ('SPORTS', 1, 'CUT', '한기대 탁구동아리🏓',
        'CUT은 탁구를 즐기며 친목을 다지는 동아리입니다.',
        'https://static.koreatech.in/upload/LOST_ITEMS/2025/6/12/bbacbbb4-5f64-4582-8f5f-e6e446031362/1000035027.jpg',
        '학생회관 102호'),
       ('PERFORMANCE', 1, 'K-오케스트라', '아름다운 음악과 재미있는 합주!',
        'K-오케스트라는 음악적 재능을 함께 나누고 성장하는 동아리입니다.',
        'https://static.koreatech.in/upload/LOST_ITEMS/2025/6/15/e12716ab-d5bc-4143-9101-5a2b6f0bfb94/1000014263.jpg',
        '학생회관 103호'),
       ('SPORTS', 1, '스텝업', '클라이밍 붐은 온다. 🧗',
        '스텝업은 클라이밍을 배우고 체력을 기르는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/7/7/a72b37fb-e82b-4cbb-a2c2-4c59d8fc6b84/923ECFF9-871B-40A3-A13A-8230F0B666F8.jpeg',
        '학생회관 104호'),
       ('ACADEMIC', 1, 'K-ROAD', 'K-ROAD는 자율주행 연구와 대회 참가로 성과를 내는연구 단체입니다.',
        'K-ROAD는 자율주행 연구와 대회 참가를 통해 실력을 쌓는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/7/8/7b60e632-0d24-4200-9891-a6dc15a72330/IMG_6794.png',
        '학생회관 105호'),
       ('SPORTS', 1, 'S.A.M', '안녕하세요! 스쿼시 동아리 S.A.M 입니다!',
        'S.A.M은 스쿼시를 즐기며 체력과 친목을 다지는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/7/17/446479f5-c109-48c5-bd63-f38942ef356d/sam 로고 반전.jpg',
        '학생회관 106호'),
       ('SPORTS', 1, 'SMASH', '한국기술교육대학교 테니스 동아리',
        'SMASH는 테니스를 배우고 실력을 향상시키는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/7/30/611ddcef-faa9-4302-8112-092ea3a48e67/1000031983.jpg',
        '학생회관 107호'),
       ('RELIGION', 1, 'SED-TUA', '한기대 가톨릭/천주교 동아리',
        'SED-TUA는 종교 활동과 봉사로 함께 성장하는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/8/6/34c9902e-fbc7-4e5e-96f2-8e53bfe601b4/1000003833.jpg',
        '학생회관 108호'),
       ('PERFORMANCE', 1, '비상', '낭만과 행복이 가득한 어쿠스틱 기타 공연 동아리',
        '비상은 기타 공연과 음악 활동을 즐기는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/8/8/84a933e3-4473-45e3-9057-cc573acdb982/1000034369.png',
        '학생회관 109호'),
       ('HOBBY', 1, '셔터', '안녕하세요! 한국기술대학교 사진 동아리 ''셔터''입니다!',
        '셔터는 사진 촬영과 편집을 즐기는 학생들의 모임입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/8/16/429d1be5-da62-4f53-b033-f6e01a55feeb/5763.png',
        '학생회관 110호'),
       ('PERFORMANCE', 1, '극예술연구회', '행동하는 젊음! 연극을 만들고 낭만을 새기는 동아리, 극예술연구회입니다.',
        '극예술연구회는 연극과 공연을 제작하며 창의력을 키우는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/9/3/f3821e52-c695-4482-8114-862e8bde4527/9498.png',
        '학생회관 111호'),
       ('PERFORMANCE', 1, '한소리', '한기대 유일무이 풍물패 입니다!',
        '한소리는 풍물 연주와 전통 문화 체험을 함께 즐기는 동아리입니다.',
        'https://static.koreatech.in/upload/CLUB/2025/10/13/c23361f0-f7ff-4eee-ae9c-7577d5bab4da/1000006554.jpg',
        '학생회관 112호');

-- 태그
INSERT INTO club_tag (name)
VALUES ('IT'),
       ('프로그래밍'),
       ('스터디'),
       ('프로젝트'),
       ('탁구'),
       ('운동'),
       ('음악'),
       ('합주'),
       ('공연'),
       ('클라이밍'),
       ('자율주행'),
       ('연구'),
       ('대회'),
       ('스쿼시'),
       ('테니스'),
       ('가톨릭'),
       ('종교'),
       ('봉사'),
       ('기타'),
       ('사진'),
       ('촬영'),
       ('연극'),
       ('예술'),
       ('풍물'),
       ('전통');

-- 동아리 태그 매핑
INSERT INTO club_tag_map (club_id, tag_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (2, 5),
       (2, 6),
       (3, 7),
       (3, 8),
       (3, 9),
       (4, 10),
       (4, 6),
       (5, 11),
       (5, 12),
       (5, 13),
       (6, 14),
       (6, 6),
       (7, 15),
       (7, 6),
       (8, 16),
       (8, 17),
       (9, 7),
       (9, 9),
       (9, 19),
       (10, 20),
       (10, 21),
       (11, 22),
       (11, 23),
       (12, 24),
       (12, 25);

-- 동아리 직책
INSERT INTO club_position (club_id, name, club_position_group)
VALUES (1, '회장', 'PRESIDENT'),
       (1, '부회장', 'PRESIDENT'),
       (1, '총무', 'MANAGER'),
       (1, '일반 회원', 'MEMBER'),
       (2, '회장', 'PRESIDENT'),
       (2, '부회장', 'PRESIDENT'),
       (2, '총무', 'MANAGER'),
       (2, '일반 회원', 'MEMBER'),
       (3, '회장', 'PRESIDENT'),
       (3, '부회장', 'PRESIDENT'),
       (3, '총무', 'MANAGER'),
       (3, '일반 회원', 'MEMBER'),
       (4, '회장', 'PRESIDENT'),
       (4, '부회장', 'PRESIDENT'),
       (4, '총무', 'MANAGER'),
       (4, '일반 회원', 'MEMBER'),
       (5, '회장', 'PRESIDENT'),
       (5, '부회장', 'PRESIDENT'),
       (5, '총무', 'MANAGER'),
       (5, '일반 회원', 'MEMBER'),
       (6, '회장', 'PRESIDENT'),
       (6, '부회장', 'PRESIDENT'),
       (6, '총무', 'MANAGER'),
       (6, '일반 회원', 'MEMBER'),
       (7, '회장', 'PRESIDENT'),
       (7, '부회장', 'PRESIDENT'),
       (7, '총무', 'MANAGER'),
       (7, '일반 회원', 'MEMBER'),
       (8, '회장', 'PRESIDENT'),
       (8, '부회장', 'PRESIDENT'),
       (8, '총무', 'MANAGER'),
       (8, '일반 회원', 'MEMBER'),
       (9, '회장', 'PRESIDENT'),
       (9, '부회장', 'PRESIDENT'),
       (9, '총무', 'MANAGER'),
       (9, '일반 회원', 'MEMBER'),
       (10, '회장', 'PRESIDENT'),
       (10, '부회장', 'PRESIDENT'),
       (10, '총무', 'MANAGER'),
       (10, '일반 회원', 'MEMBER'),
       (11, '회장', 'PRESIDENT'),
       (11, '부회장', 'PRESIDENT'),
       (11, '총무', 'MANAGER'),
       (11, '일반 회원', 'MEMBER'),
       (12, '회장', 'PRESIDENT'),
       (12, '부회장', 'PRESIDENT'),
       (12, '총무', 'MANAGER'),
       (12, '일반 회원', 'MEMBER');

-- 동아리 멤버
INSERT INTO club_member (club_id, user_id, club_position_id, is_fee_paid)
VALUES (1, 1, 1, true),
       (1, 2, 2, true),
       (1, 3, 3, false),
       (1, 5, 4, true),
       (1, 7, 4, true),
       (2, 2, 5, true),
       (2, 4, 6, false),
       (2, 6, 8, true),
       (2, 8, 8, false),
       (2, 10, 8, true),
       (2, 1, 8, true),
       (3, 1, 9, true),
       (3, 2, 12, false),
       (3, 9, 12, true),
       (4, 4, 13, true),
       (4, 6, 16, true),
       (4, 12, 16, false),
       (5, 3, 17, true),
       (5, 7, 18, false),
       (5, 1, 19, true),
       (5, 11, 20, true),
       (5, 15, 20, false),
       (6, 5, 21, true),
       (6, 8, 24, true),
       (6, 1, 24, false),
       (7, 9, 25, true),
       (7, 10, 28, true),
       (7, 16, 28, false),
       (8, 11, 29, true),
       (8, 12, 32, false),
       (8, 17, 32, true),
       (9, 14, 33, true),
       (9, 18, 36, true),
       (10, 6, 37, false),
       (10, 15, 40, true),
       (10, 19, 40, false),
       (11, 8, 41, true),
       (11, 13, 44, true),
       (11, 20, 44, false),
       (12, 2, 45, true),
       (12, 5, 46, false),
       (12, 9, 48, true),
       (12, 14, 48, false);

INSERT INTO club_recruitment (club_id, start_date, end_date)
VALUES (1, '2025-11-30', '2025-12-31'),
       (2, '2025-11-29', '2025-12-31'),
       (3, '2025-11-28', '2025-12-31'),
       (4, '2025-11-27', '2025-12-31');

INSERT INTO council (name, image_url, university_id, introduce, personal_color, location, phone_number, email, instagram_url, operating_hour)
VALUES ('개화', 'https://static.koreatech.in/upload/CLUB/2025/6/10/d0320625-7055-4a33-aad7-ee852a008ce7/BCSD Logo-symbol.png', 1,
        '총동아리연합회는 한국기술교육대학교 내 모든 동아리의 활동을 지원하고 관리하는 학생 자치 기구입니다.\n\n동아리 간의 원활한 소통을 증진하고, 동아리 문화 발전을 위해 다양한 행사와 지원 프로그램을 운영하고 있습니다.\n\n동아리 운영에 필요한 각종 행정 지원, 예산 지원, 시설 관리 등을 담당하며, 동아리 박람회, 축제 등 대형 행사를 주관합니다.',
        '#C9DEF3', '학생회관 2층 202호', '041-560-1234', 'council@koreatech.ac.kr',
        'https://www.instagram.com/koreatech_council', '평일 09:00 ~ 18:00');

INSERT INTO council_notice (council_id, title, content)
VALUES (1, '2025학년도 2학기 동아리 지원금 신청 안내',
        '안녕하세요, 총동아리연합회입니다.\n\n2025학년도 2학기 동아리 지원금 신청을 다음과 같이 안내드립니다.\n\n■ 신청 기간\n- 2025년 12월 10일(화) ~ 12월 20일(금) 18:00까지\n\n■ 지원 대상\n- 정동아리 및 준동아리로 등록된 모든 동아리\n- 2학기 활동 계획서를 제출한 동아리\n\n■ 지원 금액\n- 정동아리: 최대 500,000원\n- 준동아리: 최대 300,000원\n\n■ 신청 방법\n1. 총동아리연합회 홈페이지 접속\n2. 지원금 신청서 다운로드\n3. 활동 계획서 및 예산 계획서 작성\n4. 이메일(council@koreatech.ac.kr)로 제출\n\n■ 제출 서류\n- 동아리 지원금 신청서\n- 2학기 활동 계획서\n- 예산 사용 계획서\n- 동아리 등록증 사본\n\n■ 심사 기준\n- 활동 계획의 구체성 및 실현 가능성\n- 예산 계획의 적정성\n- 지난 학기 활동 실적\n\n■ 결과 발표\n- 2025년 12월 27일(금) 개별 공지\n\n기타 문의사항은 총동아리연합회실(학생회관 2층 202호) 또는 이메일로 연락 주시기 바랍니다.\n\n감사합니다.'),
       (1, '동아리 박람회 참가 신청 마감 안내',
        '안녕하세요, 총동아리연합회입니다.\n\n2026학년도 신입생 환영 동아리 박람회 참가 신청 마감을 안내드립니다.\n\n■ 행사 개요\n- 행사명: 2026 신입생 환영 동아리 박람회\n- 일시: 2026년 3월 5일(수) ~ 3월 6일(목) 10:00~17:00\n- 장소: 대학본부 앞 광장\n\n■ 참가 신청 마감\n- 마감일: 2025년 12월 15일(일) 23:59\n- 신청 방법: 구글 폼을 통한 온라인 신청\n- 신청 링크: https://forms.gle/example\n\n■ 부스 배정\n- 1차 추첨: 2025년 12월 18일(수)\n- 부스 위치 공지: 2025년 12월 20일(금)\n\n■ 참가 동아리 혜택\n- 동아리 홍보 부스 제공 (2m x 2m)\n- 홍보 현수막 게시 지원\n- 박람회 홍보 포스터에 동아리명 게재\n\n■ 준비 사항\n- 동아리 소개 자료 (포스터, 리플렛 등)\n- 체험 프로그램 (선택사항)\n- 신입 부원 모집 양식\n\n■ 주의 사항\n- 마감일 이후 신청 불가\n- 부스 배정 후 참가 취소 시 다음 학기 행사 참가 제한\n- 안전 관리 및 뒷정리는 각 동아리 책임\n\n많은 동아리의 참여 부탁드립니다.\n\n문의: 총동아리연합회 (041-560-1234)'),
       (1, '총동아리연합회(개화) 신입 국원 추가 모집 안내',
        '안녕하세요, 총동아리연합회 개화입니다.\n\n2025학년도 2학기 총동아리연합회 신입 국원을 추가 모집합니다.\n\n■ 모집 부서 및 인원\n- 기획부: 2명\n- 홍보부: 2명\n- 복지부: 1명\n- 총무부: 1명\n\n■ 지원 자격\n- 한국기술교육대학교 재학생 (휴학생 지원 가능)\n- 동아리 활동 경험자 우대\n- 학년 및 전공 무관\n\n■ 활동 내용\n- 동아리 지원 사업 기획 및 운영\n- 동아리 행사 준비 및 진행\n- 동아리 간 소통 및 협력 지원\n- 동아리 예산 관리 및 집행\n\n■ 활동 혜택\n- 총동아리연합회 활동 인증\n- 각종 행사 기획 및 운영 경험\n- 동아리 네트워크 형성\n- 총동아리연합회 MT 및 워크샵 참가\n\n■ 지원 기간\n- 2025년 12월 3일(화) ~ 12월 13일(금) 18:00\n\n■ 지원 방법\n1. 지원서 다운로드 (총동아리연합회 인스타그램 또는 이메일 요청)\n2. 지원서 작성 후 이메일 제출\n3. 서류 합격자 개별 연락 (12월 16일)\n4. 면접 진행 (12월 18일~19일)\n\n■ 선발 일정\n- 서류 접수: ~12월 13일(금)\n- 서류 합격자 발표: 12월 16일(월)\n- 면접: 12월 18일(수)~19일(목)\n- 최종 합격자 발표: 12월 20일(금)\n\n■ 제출 서류\n- 지원서 1부\n- 자기소개서 1부\n- 포트폴리오 (선택사항)\n\n동아리 문화 발전에 함께할 열정적인 분들의 많은 지원 바랍니다!\n\n문의: council@koreatech.ac.kr\n인스타그램: @koreatech_council'),
       (1, '동아리방 이용 수칙 안내',
        '안녕하세요, 총동아리연합회입니다.\n\n쾌적한 동아리방 환경 조성을 위한 이용 수칙을 안내드립니다.\n\n■ 기본 이용 수칙\n- 동아리방은 해당 동아리 부원만 이용 가능합니다\n- 이용 시간: 평일 09:00~22:00, 주말 10:00~20:00\n- 시설물 파손 시 변상 의무가 있습니다\n\n■ 청결 수칙\n- 음식물은 지정된 장소에서만 섭취 가능\n- 쓰레기는 분리수거하여 배출\n- 퇴실 시 청소 및 정리정돈 필수\n- 주 1회 대청소 실시 (각 동아리 자율)\n\n■ 안전 수칙\n- 화기 사용 금지\n- 전열기구 사용 시 안전 수칙 준수\n- 퇴실 시 전원 차단 및 시건 확인\n- 귀중품은 개인이 직접 관리\n\n■ 점검 사항\n- 매월 1회 총동아리연합회 순회 점검\n- 수칙 위반 시 경고 및 동아리방 사용 제한\n- 3회 경고 시 한 학기 사용 정지\n\n■ 시설 이용 신청\n- 프로젝터, 음향기기 등은 사전 예약 필수\n- 예약 방법: 구글 폼 또는 방문 신청\n\n여러분의 협조로 모두가 쾌적하게 이용할 수 있는 동아리방이 되기를 바랍니다.\n\n감사합니다.'),
       (1, '2025 겨울방학 동아리 시설 점검 및 보수 안내',
        '안녕하세요, 총동아리연합회입니다.\n\n2025년 겨울방학 기간 동안 동아리 시설 점검 및 보수 작업이 진행될 예정입니다.\n\n■ 점검 기간\n- 2026년 1월 6일(월) ~ 1월 24일(금)\n\n■ 점검 대상\n- 동아리방 (학생회관 3층~5층)\n- 동아리 연습실\n- 동아리 창고\n- 공용 시설 (복도, 화장실 등)\n\n■ 점검 내용\n- 전기/전등 시설 점검 및 교체\n- 냉난방 시설 점검\n- 책상, 의자 등 집기 파손 여부 확인\n- 도배, 장판 보수\n- 방역 작업\n\n■ 동아리별 협조 사항\n1. 1월 3일(금)까지 동아리방 정리 및 청소\n2. 귀중품 및 개인 물품 별도 보관\n3. 수리가 필요한 사항 사전 제출\n4. 점검 기간 중 동아리방 출입 제한\n\n■ 보수 신청\n- 신청 기간: ~12월 20일(금)\n- 신청 방법: 이메일로 보수 신청서 제출\n- 보수 범위: 기본 시설물에 한함\n- 동아리 귀책 사유 파손은 유상 수리\n\n■ 재입실 일정\n- 2026년 1월 27일(월)부터 입실 가능\n- 입실 전 청소 상태 확인 및 인수인계\n\n점검 기간 중 불편을 드려 죄송하며, 더 나은 환경을 위한 양해 부탁드립니다.\n\n문의: 총동아리연합회 (041-560-1234, council@koreatech.ac.kr)');
